name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull krishcode264/social-sphere-server:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run:  sudo docker run -d -p 8080:8080 -e MONGO_URL=${{ secrets.MONGO_URL }} -e PORT=${{ secrets.PORT }}  --name cicd-pipeline-container krishcode264/social-sphere-server:latest
