name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull krishcode264/social-sphere-server:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Delete Dangling Docker Images
      run: sudo docker images -f "dangling=true" -q | xargs -r sudo docker rmi

    - name: Run Docker Container
  
      env:
        PORT: ${{secrets.PORT}}
        MONGO_URL: ${{secrets.MONGO_URL}}
        NEXT_PUBLIC_SOCKET_SERVER_URL: ${{secrets.NEXT_PUBLIC_SOCKET_SERVER_URL}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        S3_ACCESSKEYID: ${{secrets. S3_ACCESSKEYID}}
        S3_SECREAT_ACCESSKEY: ${{secrets.S3_SECREAT_ACCESSKEY}}
        GOOGLE_CLIENT_ID: ${{secrets. GOOGLE_CLIENT_ID}} 
        GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
        WEB_CLIENT_URL: ${{secrets.WEB_CLIENT_URL}}
      run: sudo docker run -d -e PORT=$PORT -e MONGO_URL=$MONGO_URL -e NEXT_PUBLIC_SOCKET_SERVER_URL=$NEXT_PUBLIC_SOCKET_SERVER_URL -e JWT_SECRET=$JWT_SECRET -e S3_ACCESSKEYID=$S3_ACCESSKEYID -e S3_SECREAT_ACCESSKEY=$S3_SECREAT_ACCESSKEY -e GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET -e WEB_CLIENT_URL=$WEB_CLIENT_URL --name cicd-pipeline-container -p 8080:8080 krishcode264/social-sphere-server