name: Ping Render API

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:        # allows manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping Render API
        run: curl -m 30 -s -o /dev/null -w "%{http_code}" https://api.socialsphere.krishcode264.online
